name       : camlp4
version    : 4.13.0
release    : 5
source     :
    - https://github.com/camlp4/camlp4/archive/refs/tags/4.13+1.tar.gz : 1854eee6007af5ea746e82535bde052d465d9fefda29a2080e84e2bcb2c89ed9
license    : LGPL-2.1-only
component  : programming.library
summary    : Camlp4 is a software system for writing extensible parsers for programming languages.
description: |
    Camlp4 is a software system for writing extensible parsers for programming languages. It provides a set of OCaml libraries that are used to define grammars as well as loadable syntax extensions of such grammars. Camlp4 stands for Caml Preprocessor and Pretty-Printer and one of its most important applications is the definition of domain-specific extensions of the syntax of OCaml.
builddeps  :
    - git
    - ocaml
    - ocamlbuild
rundeps    :
    - ocaml
setup      : |
    ./configure --bindir=/usr/bin --libdir=%libdir%
build      : |
    %make
install    : |
    %make_install
