name       : camlp4
version    : 4.06.1
release    : 2
source     :
    - https://github.com/ocaml/camlp4/archive/4.06+1.tar.gz : b1cc51449da0537f6886e380815b716e7adc9d9a12d6098a06db2b2525bab922
license    : LGPL-2.1-only
component  : programming.library
summary    : Camlp4 is a software system for writing extensible parsers for programming
    languages.
description: |
    Camlp4 is a software system for writing extensible parsers for programming languages. It provides a set of OCaml libraries that are used to define grammars as well as loadable syntax extensions of such grammars. Camlp4 stands for Caml Preprocessor and Pretty-Printer and one of its most important applications is the definition of domain-specific extensions of the syntax of OCaml.
builddeps  :
    - git
    - ocaml
    - ocamlbuild
rundeps    :
    - ocaml
setup      : |
    ./configure --bindir=/usr/bin --libdir=%libdir%
build      : |
    %make
install    : |
    %make_install
